name: Deploy to GitHub Pages

on:
  # Chạy khi có push vào branch main
  push:
    branches: [ "main" ]
  
  # Cho phép chạy workflow thủ công từ Actions tab
  workflow_dispatch:

# Thiết lập quyền GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages